### ISSUE TITLE
AWS API fails because lower case codingkeys

### ISSUE THREAD

**Issue by joscdk** [amzn/smoke-aws#10] opened 2019-02-16 02:21 UTC
When launching an instance, a lot of nested keys fails. There are some examples here:

`deleteOnTermination` should have `= "DeleteOnTermination"
https://github.com/amzn/smoke-aws/blob/0.16.9/Sources/ElasticComputeCloudModel/ElasticComputeCloudModelStructures.swift#L11575

`deviceName` should have `= "DeviceName"`
https://github.com/amzn/smoke-aws/blob/0.16.9/Sources/ElasticComputeCloudModel/ElasticComputeCloudModelStructures.swift#L1394

There are more, however here are a couple of examples.

**Comment by tachyonics** [comment] 2019-02-26 23:29
Thanks for opening this issue. I'll take a look at it.

**Comment by tachyonics** [comment] 2019-03-02 17:05
It looks like this is due to a deviation between the published model[1] and the API Reference[2]. Looks like it is consistent for the EC2 service so I think there is a straight forward path forward to capitalise all request keys.

I will verify with the runInstances API.

[1] https://github.com/aws/aws-sdk-go/blob/master/models/apis/ec2/2016-11-15/api-2.json#L19335-L19337
[2] https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_BlockDeviceMapping.html

**Comment by tachyonics** [comment] 2019-03-26 20:18
I have been able to reproduce the issue and identify a fix that I have been able to test by starting an instance with an attached Ebs volume. There are changes across SmokeHTTP and SmokeAWS. I have just published the pull request for SmokeHTTP.

**Comment by joscdk** [comment] 2019-03-26 20:24
@tachyonics sweet, thank you very much, then i can switch away from my own hacked fork :D .. I might give it a go if i find some free time tonight :)

**Comment by tachyonics** [comment] 2019-03-27 00:57
@joscdk The changes to this package are now pushed to the `fix_query_errors_ec2_keys` branch. Let me know if you are still having issues.

**Comment by tachyonics** [comment] 2019-06-06 16:19
@joscdk Were you able to verify that this fixed your issue?

**Comment by joscdk** [comment] 2019-06-06 16:27
@tachyonics no sorry, we have had an insanely tight deadline on our project, so i am still using my own fork for this and 18.04 support .. I will see if i can try to switch it out during the weekend as a test :)

**Comment by tachyonics** [comment] 2021-02-24 11:08
Closing this issue has its long been fixed in the codebase and we were waiting on verification of fix.

**Closed by tachyonics** 2021-02-24 11:08 UTC
